### ISSUE TITLE
Migrate to ee4j

### ISSUE THREAD

**Issue by keilw** [eclipse-ee4j/nosql#1]
This repository should be transferred to https://github.com/eclipse-ee4j

**Comment by otaviojava** [comment]
Yes, we're waiting for the Eclipse Process, there is a ticket for that.

**Comment by otaviojava** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=548064

**Comment by otaviojava** [comment]
That is the place, done :)
