### ISSUE TITLE
ReactiveStreams/Flow support

### ISSUE THREAD

**Issue by hantsy** [eclipse-ee4j/nosql#108]
almost all data related  project, such as Spring Data, MicroauntData have added ReactiveStreams/Flow support, Jakarta EE/MP also includes a ReactiveStreams operates spec. 

Consider ReactiveStreams or Java Flow support.

**Comment by otaviojava** [comment]
We have this in mind.
We also have this on the implementation:

https://github.com/eclipse/jnosql/tree/main/jnosql-mapping/jnosql-mapping-reactive

We're using the Jakarta Reactive.

We still waiting for the decision about the relationship between Jakarta and MicroProfile:

* Can we use it on the spec?
* Should we replicate it on the Jakarta EE side?
* Who will support the same API twice?
