### ISSUE TITLE
Define Parent

### ISSUE THREAD

**Issue by keilw** [eclipse-ee4j/nosql#11]
Define a Parent like all other Jakarta EE Specs:
```
    <parent>
        <groupId>org.eclipse.ee4j</groupId>
        <artifactId>project</artifactId>
        <version>1.0.5</version>
    </parent>
```

**Comment by otaviojava** [comment]
are you sure?
The pom,.xml does not have anything.
https://mvnrepository.com/artifact/org.eclipse.ee4j/project/1.0.5

**Comment by otaviojava** [comment]
Fixed, thank you @keilw
