### ISSUE TITLE
Handle DbRef in Mongo

### ISSUE THREAD

**Issue by hantsy** [eclipse-ee4j/nosql#110]
Mongo drivers itself can handle the dbref case. 

```json
{
  'title': 'test title', 
  'comments': [ uuid-1, 2, 3] //ref to comment document
}
```

we can add and remove comment from Post.comments node directly.

**Comment by otaviojava** [comment]
Hey @hantsy 
I hope that you're okay.

Once it is a particular behavior, I'll move it to an extension:
https://github.com/eclipse/jnosql-mapping-extension/tree/main/jnosql-mongodb-extension

The goal of the NoSQL API is to use the commons behavior, anything else, move to extension.
