### ISSUE TITLE
Create change log file to each repository

### ISSUE THREAD

**Issue by otaviojava** [eclipse-ee4j/nosql#118]
A changelog is a file containing a curated, chronologically ordered list of notable changes for each project version.

Reference:

* https://keepachangelog.com/en/1.0.0/

**Comment by DanSilva41** [comment]
Hi @otaviojava,
I opened a pull request, could you check if I'm doing it right please.

https://github.com/eclipse-ee4j/nosql/pull/126

I also leave it open for us to discuss about issues references and author names in the CHANGELOG files, as well as other points!

**Comment by DanSilva41** [comment]
Hi, @otaviojava!
I started working on the other changelog files, and I noticed that lately you raised the use of asciidoc.
Does it make sense to format changelog files to asciidoc?

**Comment by otaviojava** [comment]
Yeap, it does!

**Comment by DanSilva41** [comment]
@otaviojava, I opened last PR about changelog files.

**Comment by otaviojava** [comment]
@DanSilva41 thank you, and well done.
