### ISSUE TITLE
Refactoring Spec at Jakarta NoSQL

### ISSUE THREAD

**Issue by otaviojava** [eclipse-ee4j/nosql#120]
At the spec, we have several concepts around NoSQL and their definition. To reduce and make the spec more cohesive, we can reduce it by removing what does not belong to API and putting links instead.

**Comment by andradesampaio** [comment]
Hi @otaviojava,
Forgive my ignorance, I opened a merge request, could you check if I'm doing it right please.
https://github.com/eclipse-ee4j/nosql/pull/123
