### ISSUE TITLE
Include select and delete methods on Document and Column template specializations

### ISSUE THREAD

**Issue by otaviojava** [eclipse-ee4j/nosql#148]
Currently, we have two query instances for both Document and Column types.

The proposal is to increase the experience by adding two methods on both Document and Column templates.

```java
@Inject
DocumentTemplate template;

List<Book> books = template.select(Book.class).where("category").eq("Java").execute();

template.delete(Person.class).where("id").eq("id").execute();
```

Both will work with the fluent query API style.

**Comment by njr-11** [comment]
What you proposed above looks compatible with SQL/JPQL. Should it be done under Jakarta Data instead so that it can be standardized across all?

**Comment by otaviojava** [comment]
Currently, we still need the template interface.

It might be an excellent next step when we finish the repositories types.

I like the idea.
