### ISSUE TITLE
Consider adding an "api" module?

### ISSUE THREAD

**Issue by keilw** [eclipse-ee4j/nosql#15]
Similar to the name of the spec module (#14) almost every Jakarta EE repository follows a common pattern with an "api" Maven module for API code. We could/should move [communication](https://github.com/eclipse-ee4j/nosql/tree/master/communication) and [mapping](https://github.com/eclipse-ee4j/nosql/tree/master/mapping) under an `api` layer.

**Comment by otaviojava** [comment]
These modules already are API, I think that will be redundant.

Ref:
https://docs.oracle.com/javase/8/docs/technotes/guides/jdbc/

**Comment by keilw** [comment]
Well they would just be a Parent POM, see https://github.com/eclipse-ee4j/websocket-api/tree/master/api which has "client" and "server" under its "api". It was only a first step, but don't mistake the root POM for that parent, it should change to <groupId>org.eclipse.ee4j.websocket</groupId> as soon as https://github.com/eclipse/jnosql/issues/195 gets resolved.
