### ISSUE TITLE
Upgrading the API for exploring Java 17 style

### ISSUE THREAD

**Issue by otaviojava** [eclipse-ee4j/nosql#152]
Following the Jakarta Data issue about the topic: 
https://github.com/jakartaee/data/issues/70

The goal is to remove all get as the prefix on the methods, such as `getResult`, `getSingleResult`, and convert those to `result` and `singleResult`.

This issue will break compatibility with the previous version.

**Comment by zaim1hassaniadili** [comment]
Hello,
I would like to contribute to that issue. Just to be sure, I have to rename all API accessor from ``getSomething`` to ``something``.
though, I don't understand the implication with the adoption of java 17, in the topic jakartaee/data#70.
Thanks.

**Comment by otaviojava** [comment]
Hey @zaim1hassaniadili, the goal is to follow the same code style.

**Comment by otaviojava** [comment]
I'll close this one once we move it to the JNoSQL project.
