### ISSUE TITLE
A deep review of Jakarta NoSQL after the only mapping decision

### ISSUE THREAD

**Issue by otaviojava** [eclipse-ee4j/nosql#155]
After we decided to move Jakarta NoSQL only with the Mapping side and the regular part, we removed a considerable amount of code keeping:

The template interfaces
Mapping annotations

The goal would be to review and check the following points:

- [x] Check if the README file is updated.
- [x] Check if the spec has been updated.
- [x] Check if the JavaDoc is ready.

Also, you can say that all feedbacks are welcome.

**Comment by mpredli01** [comment]
Hey @otaviojava:

Overall, this looks good, but there are references to the Communication API and, since this is now aligned with Jakarta EE 10, the reference to the namespace change can be removed.

I will look at this in more detail later today or tomorrow morning.

**Comment by otaviojava** [comment]
Thanks @mpredli01
