### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by keilw** [eclipse-ee4j/nosql#2]
Even though as Jakarta EE spec this is new, it follows what was incubating under https://github.com/eclipse/jnosql/releases in release 0.0.9, so this new spec may better stick to 0.1.0-SNAPSHOT instead of going back to 0.0.1.

**Comment by otaviojava** [comment]
You're right.
I'll fix it.

**Comment by otaviojava** [comment]
Fixed on: https://github.com/eclipse-ee4j/nosql/issues/2
