### ISSUE TITLE
Create a TCK

### ISSUE THREAD

**Issue by keilw** [eclipse-ee4j/nosql#20]
Either in a separate repository (as many Jakarta EE specs do) or theoretically as a module (then #15 would become mandatory to tell API and TCK apart) here we should create a TCK soon.

**Comment by otaviojava** [comment]
Yes, but, baby-steps.
First, we need to have a stable API; then we can work on the TCK.
After these discussions, I would like to release a version to the community to see the result, and then we can start to work on the TCK.

**Comment by keilw** [comment]
The TCK is not exactly the same, see the 1000+ tests in https://github.com/unitsofmeasurement/indriya and the https://github.com/unitsofmeasurement/unit-tck. A few tests could be usable. I guess the experience of Jakarta EE 8 with creating and opening several dozen TCKs right now might help to find the right toolset as well (e.g. TestNG vs. JUnit or Arquillian, etc.)
