### ISSUE TITLE
Licenses?

### ISSUE THREAD

**Issue by keilw** [eclipse-ee4j/nosql#3]
The structurally identical JNoSQL "spec" had the following licenses: https://github.com/eclipse/jnosql/blob/master/LICENSE
This one https://github.com/JNOSQL/nosql/blob/master/LICENSE while upgraded to EPL 2.0 does not mention the Apache License 2.0 as secondary license at all, it's lost and "replaced" by the default Java EE 8 "legacy" of GPL 2 with CPE.
How come the secondary license would suddenly change, or was it a template mistake?

**Comment by otaviojava** [comment]
This request comes from the legal team.

**Comment by keilw** [comment]
Eclipse Legal? @waynebeaton, is this really the case, that new Jakarta EE Specs must have GPL with CPE as the only secondary license, regardless of the prior codebase?

**Comment by waynebeaton** [comment]
It came from me. While the project proposal was in draft, I expressed a preference that the project use the licensing scheme of the top-level project. @otaviojava agreed.

**Comment by keilw** [comment]
I don't see that much of a problem, are there others including every contributor (https://github.com/eclipse/jnosql/graphs/contributors) who should be asked for their permission (I know from a Spec Lead role, that is the case for JCP specs) or can the project lead decide that alone? 
Also asking with other possible candidates like Config in mind. I highly doubt they would accept that based on what's going on with MicroPofile, but if those who need to approve the license change are happy for NoSQL, I see no problem. Given Jakarta Persistence uses the same license it might also make it easier where synergies could arise ;-)

**Comment by otaviojava** [comment]
@waynebeaton thank you.

**Comment by waynebeaton** [comment]
The IP Team is engaged. They will ensure that any relicensing that is required has been executed correctly.

**Comment by struberg** [comment]
Also note, that the current API is licensed under EPL-1.0.
This potentially needs further clearance and ACK from all contributors if you want to update to EPL-2.0.

**Comment by keilw** [comment]
That's why I asked, but it does not seem an issue. For most parts @otaviojava was the only contributor anyway ;-)

**Comment by otaviojava** [comment]
Thank for the feedbacks, that is the IP track: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=19915

**Comment by waynebeaton** [comment]
> Also note, that the current API is licensed under EPL-1.0.
> This potentially needs further clearance and ACK from all contributors if you want to update to EPL-2.0. 

Content licensed under the EPL-1.0 can be distributed under the terms of a new version of the agreement. That is, you can just update the license from EPL-1.0 to EPL-2.0. It's a good idea to let contributors know what you're doing.

FWIW, updating from EPL-1.0 to EPL-2.0 with a secondary license (which I believe is the case here) may require some attention from the contributors. The IP should have noticed this when you submitted your initial contribution for their review and provided assistance for remediation. If you're not sure, send a note to license@eclipse.org to ask for advice.

> The linked document also lists ALv2 btw.
> https://github.com/eclipse-ee4j/nosql/blob/master/specification/src/main/resources/META-INF/LICENSE#L3

**Comment by keilw** [comment]
The project info https://projects.eclipse.org/projects/ee4j.nosql states GPL with CPE as the secondary license, which one is correct, or are there 2 secondary licenses?

**Comment by keilw** [comment]
This is very old, @otaviojava, @waynebeaton, @ivargrimstad do you see any reason to keep it open?

**Comment by otaviojava** [comment]
IMHO, we can close this one.
