### ISSUE TITLE
Consider making samples more neutral

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/nosql#61]
Given the world we live in, I think it would be better to avoid using entities which may be seen inappropriate by some as they may be interpreted as referring to [a particular religion](https://www.learnreligions.com/god-or-god-to-capitalize-or-not-to-capitalize-249823). Ie github itself tries to be on [the safe side](https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/)

**Comment by keilw** [comment]
Are you suggesting to remove all God examples including the Greek or Nordic ones?

I don't think Jakarta NoSQL even uses Egyptian gods, the majority of examples are under https://github.com/JNOSQL and demos like https://github.com/JNOSQL/nosql-endgame refer to the "Avengers" characters, at most Marvel could find some of them offensive, but as Thor existed before the Marvel films I think we should be safe.

I asked the Platform project or Spec Committee about that whole "master" renaming and at least until Jakarta EE 9 is final, that is out of discussion, it would disrupt far more build pipelines there than for NoSQL.

**Comment by lukasj** [comment]
What I'm suggesting is to avoid using the entity named "God" as it may refer to one particular religion, Christianity should it be not clear enough.

I really do not care when/if the "master" renaming in our repos is going to happen. My point is to show an example of someone else close enough to us moving to politically correct naming convention in order to prevent association with possibly offending context.

**Comment by keilw** [comment]
So is it more about being fair to atheists or those worshipping Satan or the Pastafari monster? We'll consider it. We may have to change some demos on @thodorisbais' part because the ancient mythology won't work that well without a "God" entity, while the Avengers themed examples could use a term like "Hero" instead.

**Comment by lukasj** [comment]
> So is it more about being fair to atheists or those worshipping Satan or the Pastafari monster?

Do you think those killing people in churches in France are Satanists or Pastafarians?

**Comment by keilw** [comment]
Some may say, but we're not picturing any of those gods (especially no Muslim ones) and "Allah" is simply the translation of "God" but we also have i18n cases in other projects, therefore I don't really see a problem with a particular word.

**Comment by otaviojava** [comment]
I don't know, but it easier to change it to Hero instead of God.
I'll create a PR later today.

Thank you for the feedback @lukasj

**Comment by keilw** [comment]
Is this only about the textual samples here I assume, because the actual examples are found in places like https://github.com/JNOSQL.
Please do not create or merge a PR there until our Devoxx talk is over, it may cause too much disruption there, but we can change it over the weekend ;-)

**Comment by lukasj** [comment]
thank you @otaviojava

**Comment by otaviojava** [comment]
@lukasj https://github.com/eclipse-ee4j/nosql/pull/63

**Comment by keilw** [comment]
@lukasj @otaviojava Sorry but that PR makes no real sense. If you want to continue down the "Heroes" path, then please let's do it properly and move from Greek Gods to Greek Heroes in this case by using folks like Odysseus (https://quizlet.com/109848802/odyssey-flash-cards/) or Archilles.

**Comment by lukasj** [comment]
[merriam-webster](https://www.merriam-webster.com/thesaurus/god) to the rescue, it lists bunch of synonyms one can use. While _hero_ is one of the synonyms, either _deity_ or _divinity_ probably fits better.

**Comment by keilw** [comment]
@lukasj @merriam-webster Thanks a lot, it seems to also work with `demideity` in some of the examples. 
We might go with the "Hero" approach in some examples like "NoSQL Endgame", but let's use this in all other places.
@otaviojava can you fix the PR accordingly?

**Comment by thodorisbais** [comment]
@lukasj thank you for bringing this up, but before making any change to our nosql-endgame presentation/repository, I would be interested in hearing whether your stand represents you as an open-source entity or your employer.

**Comment by keilw** [comment]
If we do it here it should be consistent, so @lukasj, @thodorisbais please advise or discuss before I can approve https://github.com/eclipse-ee4j/nosql/pull/63

**Comment by thodorisbais** [comment]
@keilw exactly the reason I'm questioning the rationale, so let's see what the outcome of this discussion will be :-)

**Comment by keilw** [comment]
I think @lukasj also explained to some extent why he thinks it is better to use a more neutral term like "Deity" because "God" is also used as the name more often than the attribute or position. 
The "master/slave" discussion is similar to what some people say about the [Zwarte Piet](https://en.wikipedia.org/wiki/Zwarte_Piet#Public_opinion_in_the_Low_Countries_and_worldwide), or what's been happening anywhere from Pim Fortuyn to his successor Wilders or Theo van Gogh...

**Comment by lukasj** [comment]
@thodorisbais does it matter whose stand the issue represents? Does my employer's opinion have different weight than my - or arbitrary contributor's - own? If the answer is yes and this project is supposed to be open then I'm sorry but that approach smells as I was hoping all input is treated equally.

**Comment by thodorisbais** [comment]
@lukasj I'm sorry if you got me wrong, that was not my intention, Lukas. I would be equally happy regardless of where this came from, it was just a friendly question to understand the rationale behind this and whether there is already such an agreement on the table (or up for discussion), which would mean that we would need to rigorously reassess the rest of the projects as well :-) .

**Comment by keilw** [comment]
I can't say, if the spec is currently important enough to Oracle, but with JUGs e.g. from Turkey adopting some other specs already I'd say we don't take a risk offending any of them so let's use the neutral term. @lukasj has a point, that one benefit of Jakarta EE compared to the JCP is, that no single company like Oracle or IBM have the sole veto right, so I guess it also doesn't really matter if his company shares that opinion or have any on this topic.

**Comment by thodorisbais** [comment]
@keilw fair point as well. Let's move ahead. I'll create a new issue for our nosql-endgame repo and link it to this one.

**Comment by lukasj** [comment]
@thodorisbais Np. Thanks for your explanation. I'm pretty sure we all are sometimes lost in translation ;-)

Generally, what I do care about here are apis (incl. javadoc) and spec document - that is something what should follow some general conventions and use as much neutral language as possible. It's supposed to be published technical documentation other vendors/implementors should follow in the end. 

I understand it's hard to come up with good names and examples and, generally, I like those here as there is finally something different from Employee, Customer, Person etc.  It's just that little thing there...

**Comment by keilw** [comment]
A bit like the late Bill Shannon O;-) He also even spoke out against those e.g. in the PR department when they tried to violate conventions or ignore technical restrictions. While he left giant shoes glad a few others at Oracle also triy to walk in them ;-)
