### ISSUE TITLE
Make spec document more implementor centric

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/nosql#62]
Going through current spec, it feels to me more like a user-guide for particular implementation.
While having descriptive examples may be good thing to have there, I'd expect the spec document to be more "implementor centric" with defined requirements for the implementor. A user guide of particular implementation seems to be better place for (more) detailed examples as it may use also implementation-specific features.

**Comment by keilw** [comment]
Thanks, we appreciate input by @lukasj, @m0mus or maybe @cfsilence who I just learned about his role at Oracle during JCON last week.
