### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: javax.annotation.Priority

### ISSUE THREAD

**Issue by sergey-morenets** [eclipse-ee4j/nosql#64]
Hi

I tried to use sample from the official documentation http://www.jnosql.org/docs/document.html. However I've got a pretty strange exception:

```
Caused by: java.lang.NoClassDefFoundError: javax/annotation/Priority
	at jakarta.nosql.ServiceLoaderSort.of(ServiceLoaderSort.java:67)
```

ServiceLoaderSort class from the communication-core module(version 1.0.0-b2) is defined in jakarta.nosql package but imports type from javax projects:

`import javax.annotation.Priority;`

Is it correct behavior?

**Comment by keilw** [comment]
The most recent version should not use javax any more, but if you look at a milestone build like B02 that still would be correct. Are you talking about the SNAPSHOT or B02 state?

**Comment by sergey-morenets** [comment]
@keilw Here's my list of dependencies (I guess it's the latest published ones):

		<dependency>
			<groupId>org.eclipse.jnosql.artemis</groupId>
			<artifactId>artemis-document</artifactId>
			<version>1.0.0-b2</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.jnosql.diana</groupId>
			<artifactId>mongodb-driver</artifactId>
			<version>1.0.0-b2</version>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<scope>provided</scope>
			<version>1.18.16</version>
		</dependency>
		<dependency>
			<groupId>jakarta.platform</groupId>
			<artifactId>jakarta.jakartaee-api</artifactId>
			<version>9.0.0</version>
			<scope>provided</scope>
		</dependency>

**Comment by sergey-morenets** [comment]
@keilw BTW, is there a fixed date for Jakarta NoSQL release version?

**Comment by otaviojava** [comment]
@sergey-morenets we're not ready to version 9.0.0 yet:
https://www.eclipse.org/lists/jnosql-dev/msg00557.html
It is WIP, hopefully, we'll have a version next two weeks.
