### ISSUE TITLE
Trying to implement at OpenLiberty

### ISSUE THREAD

**Issue by asterisk360-admin** [eclipse-ee4j/nosql#68]
Hello everyone

I'm trying to implement jakarta nosql in openliberty, but i dont have success.
Dependencies are not resolved, and package jakarta.nosql.* dont exist.
The openLiberty version is  21.0.0.2

Any help is apreciated. Regards

The pom.xml used is:

<?xml version='1.0' encoding='utf-8'?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <groupId>com.module</groupId>
    <artifactId>module</artifactId>
    <version>1.0.0</version>
    <packaging>war</packaging>

    <properties>
        <maven.compiler.source>15</maven.compiler.source>
        <maven.compiler.target>15</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    </properties>

    <dependencies>
		
		<dependency>
		    <groupId>jakarta.platform</groupId>
		    <artifactId>jakarta.jakartaee-web-api</artifactId>
		    <version>8.0.0</version>
		    <scope>provided</scope>
		</dependency>
        
        <dependency>
            <groupId>org.eclipse.microprofile</groupId>
            <artifactId>microprofile</artifactId>
            <version>4.0.1</version>
            <type>pom</type>
            <scope>provided</scope>
        </dependency>
        
	<dependency>
		    <groupId>org.jnosql.diana</groupId>
		    <artifactId>diana-document</artifactId>
		    <version>0.0.9</version>
	</dependency>
	
	<dependency>
		    <groupId>org.jnosql.diana</groupId>
		    <artifactId>mongodb-driver</artifactId>
		    <version>0.0.9</version>
	</dependency>
	
	<dependency>
		    <groupId>org.jnosql.artemis</groupId>
		    <artifactId>artemis-configuration</artifactId>
		    <version>0.0.9</version>
		    <scope>provided</scope>
	</dependency>
	
	<dependency>
         	    <groupId>org.jnosql.artemis</groupId>
		    <artifactId>artemis-document</artifactId>
		    <version>0.0.9</version>
	</dependency>
	
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.18</version>
            <scope>provided</scope>
        </dependency>
		
		<dependency>
		    <groupId>com.google.code.gson</groupId>
		    <artifactId>gson</artifactId>
		    <version>2.8.6</version>
		</dependency>
	</dependencies>
	
    <build>
        <finalName>${project.artifactId}</finalName>
        <plugins>
        	
			<plugin>
			    <groupId>org.apache.maven.plugins</groupId>
			    <artifactId>maven-war-plugin</artifactId>
			    <version>3.3.1</version>
			</plugin>
            
			<plugin>
			    <groupId>io.openliberty.tools</groupId>
			    <artifactId>liberty-maven-plugin</artifactId>
			    <version>3.3.4</version>
			</plugin>
        </plugins>
    </build>

</project>

**Comment by otaviojava** [comment]
Hello, how are you?
Could you test with version 1.0.0-b3?

**Comment by keilw** [comment]
I guess that 0.0.9 is fairly outdated now, so 1.0.0b3 or at least b2 would be a better choice.

**Comment by asterisk360-admin** [comment]
Hello and thanks both for the reply.

I'm confused about to the repository to select.
Updated examples at internet talk about org.jnosql (https://www.baeldung.com/eclipse-jnosql) 
and the documentation reference to org.eclipse.jnosql  (http://www.jnosql.org/docs/document.html)

In your suggest you talk about org.jnosql but i cant find that version>
<dependency>
    <groupId>org.jnosql.artemis</groupId>
    <artifactId>artemis-document</artifactId>
    <version>1.0.0-b3</version>
</dependency>

I found this two possible options>

<dependency>
    <groupId>org.jnosql.artemis</groupId>
    <artifactId>artemis-document</artifactId>
    <version>0.0.9</version>
</dependency>

<dependency>
    <groupId>org.eclipse.jnosql.artemis</groupId>
    <artifactId>artemis-document</artifactId>
    <version>1.0.0-b2</version>
</dependency>

For openliberty wich will be the recomend implementation.
Its org.jnosql a legacy repository?

Apreciated your help.

Regards




> Hello, how are you?
> Could you test with version 1.0.0-b3?
> Be Aware that we need Eclipse MicroProfile Config
> 
> ```
> <dependency>
>    <groupId>org.jnosql.communication</groupId>
>    <artifactId>mongodb-driver</artifactId>
>    <version>1.0.0-b3</version>
> </dependency>
> <dependency>
>     <groupId>org.jnosql.artemis</groupId>
>     <artifactId>artemis-document</artifactId>
>     <version>1.0.0-b3</version>
> </dependency>
> ```
> 
> Please, let me know if it works.
> You can also share the GitHub repository.
> I'm glad to help.

**Comment by otaviojava** [comment]
Please, @asterisk360-admin use those dependencies:

https://mvnrepository.com/artifact/jakarta.nosql.mapping/mapping-document/1.0.0-b3
https://mvnrepository.com/artifact/org.eclipse.jnosql.communication/mongodb-driver/1.0.0-b3

**Comment by asterisk360-admin** [comment]
Thanks for reply @otaviojava

I get the next dependence missing error:

@Inject
@Database(DatabaseType.DOCUMENT
ERROR = DatabaseType - cannot be resolved to a variable

PersonRepository repository = container.select(PersonRepository.class).select(DatabaseQualifier.ofDocument()).get();
ERROR = DatabaseQualifier - cannot be resolved

I update the code of the example at this repo >  https://github.com/asterisk360-admin/jnosql-openliberty


Any help is apreciated. 
Regards

------

> Please, @asterisk360-admin use those dependencies:
> 
> https://mvnrepository.com/artifact/jakarta.nosql.mapping/mapping-document/1.0.0-b3
> https://mvnrepository.com/artifact/org.eclipse.jnosql.communication/mongodb-driver/1.0.0-b3

**Comment by otaviojava** [comment]
Hey @asterisk360-admin could you merge this PR?
https://github.com/asterisk360-admin/jnosql-openliberty/pull/1

**Comment by asterisk360-admin** [comment]
Nice help @otaviojava really apreciated!

Now i'm trying to use CDI but the next dependency error is show at runtime:
I see this classes are in jakarta.nosql/api-parent package
Is another dependency required for work with CDI?

I update the last test code repo> https://github.com/asterisk360-admin/jnosql-openliberty

---

[INFO] [WARNING ] CWNEN0049W: Resource annotations on the methods of the org.eclipse.jnosql.mapping.configuration.SettingsConverter class will be ignored. The annotations could not be obtained because of the exception : java.lang.NoClassDefFoundError: jakarta/nosql/Settings

[INFO] [WARNING ] CWNEN0047W: Resource annotations on the fields of the dao.Producer class will be ignored. The annotations could not be obtained because of the exception : java.lang.NoClassDefFoundError: jakarta/nosql/document/DocumentConfiguration

[INFO] [WARNING ] CWNEN0049W: Resource annotations on the methods of the dao.Producer class will be ignored. The annotations could not be obtained because of the exception : java.lang.NoClassDefFoundError: jakarta/nosql/document/DocumentConfiguration

[INFO] [WARNING ] CWNEN0047W: Resource annotations on the fields of the org.eclipse.jnosql.mapping.util.ParamsBinder class will be ignored. The annotations could not be obtained because of the exception : java.lang.NoClassDefFoundError: jakarta/nosql/NoSQLException

[INFO] [WARNING ] CWNEN0049W: Resource annotations on the methods of the org.eclipse.jnosql.mapping.util.ParamsBinder class will be ignored. The annotations could not be obtained because of the exception : java.lang.NoClassDefFoundError: jakarta/nosql/NoSQLException

[INFO] [WARNING ] CWNEN0047W: Resource annotations on the fields of the org.eclipse.jnosql.mapping.reflection.FieldMappingBuilder class will be ignored. The annotations could not be obtained because of the exception : java.lang.NoClassDefFoundError: jakarta/nosql/TypeSupplier

[INFO] [WARNING ] CWNEN0049W: Resource annotations on the methods of the org.eclipse.jnosql.mapping.reflection.FieldMappingBuilder class will be ignored. The annotations could not be obtained because of the exception : java.lang.NoClassDefFoundError: jakarta/nosql/TypeSupplier

[INFO] [WARNING ] CWNEN0047W: Resource annotations on the fields of the dao.normal.PersonDAO class will be ignored. The annotations could not be obtained because of the exception : java.lang.NoClassDefFoundError: jakarta/nosql/mapping/document/DocumentTemplate

[INFO] [WARNING ] CWNEN0047W: Resource annotations on the fields of the org.eclipse.jnosql.mapping.repository.returns.PageRepositoryReturn class will be ignored. The annotations could not be obtained because of the exception : java.lang.NoClassDefFoundError: jakarta/nosql/NoSQLException

[INFO] [WARNING ] CWNEN0049W: Resource annotations on the methods of the org.eclipse.jnosql.mapping.repository.returns.PageRepositoryReturn class will be ignored. The annotations could not be obtained because of the exception : java.lang.NoClassDefFoundError: jakarta/nosql/NoSQLException

[INFO] [WARNING ] CWNEN0047W: Resource annotations on the fields of the org.eclipse.jnosql.mapping.repository.returns.SortedSetRepositoryReturn class will be ignored. The annotations could not be obtained because of the exception : java.lang.NoClassDefFoundError: jakarta/nosql/NoSQLException

[INFO] [WARNING ] CWNEN0049W: Resource annotations on the methods of the org.eclipse.jnosql.mapping.repository.returns.SortedSetRepositoryReturn class will be ignored. The annotations could not be obtained because of the exception : java.lang.NoClassDefFoundError: jakarta/nosql/NoSQLException

[INFO] [WARNING ] CWNEN0047W: Resource annotations on the fields of the org.eclipse.jnosql.mapping.repository.DynamicReturn$SupplierConverter class will be ignored. The annotations could not be obtained because of the exception : java.lang.NoClassDefFoundError: jakarta/nosql/NonUniqueResultException

[INFO] [WARNING ] CWNEN0049W: Resource annotations on the methods of the org.eclipse.jnosql.mapping.repository.DynamicReturn$SupplierConverter class will be ignored. The annotations could not be obtained because of the exception : java.lang.NoClassDefFoundError: jakarta/nosql/NonUniqueResultException

[INFO] [WARNING ] CWNEN0049W: Resource annotations on the methods of the org.eclipse.jnosql.mapping.reflection.AbstractFieldMapping class will be ignored. The annotations could not be obtained because of the exception : java.lang.NoClassDefFoundError: jakarta/nosql/Value

[INFO] [WARNING ] CWNEN0049W: Resource annotations on the methods of the org.eclipse.jnosql.mapping.reflection.DefaultClassMappings class will be ignored. The annotations could not be obtained because of the exception : java.lang.NoClassDefFoundError: jakarta/nosql/NoSQLException

[INFO] [WARNING ] CWNEN0049W: Resource annotations on the methods of the org.eclipse.jnosql.mapping.reflection.EmbeddedFieldMapping class will be ignored. The annotations could not be obtained because of the exception : java.lang.NoClassDefFoundError: jakarta/nosql/Value

[INFO] [WARNING ] CWNEN0049W: Resource annotations on the methods of the org.eclipse.jnosql.mapping.reflection.DefaultFieldMapping class will be ignored. The annotations could not be obtained because of the exception : java.lang.NoClassDefFoundError: jakarta/nosql/Value

[INFO] [WARNING ] CWNEN0047W: Resource annotations on the fields of the org.eclipse.jnosql.mapping.reflection.GenericFieldMapping class will be ignored. The annotations could not be obtained because of the exception : java.lang.NoClassDefFoundError: jakarta/nosql/TypeSupplier

[INFO] [WARNING ] CWNEN0049W: Resource annotations on the methods of the org.eclipse.jnosql.mapping.reflection.GenericFieldMapping class will be ignored. The annotations could not be obtained because of the exception : java.lang.NoClassDefFoundError: jakarta/nosql/Value

[INFO] [WARNING ] CWNEN0047W: Resource annotations on the fields of the org.eclipse.jnosql.mapping.reflection.DefaultReflections class will be ignored. The annotations could not be obtained because of the exception : java.lang.NoClassDefFoundError: jakarta/nosql/NoSQLException

[INFO] [WARNING ] CWNEN0049W: Resource annotations on the methods of the org.eclipse.jnosql.mapping.reflection.DefaultReflections class will be ignored. The annotations could not be obtained because of the exception : java.lang.NoClassDefFoundError: jakarta/nosql/NoSQLException

[INFO] [WARNING ] CWNEN0049W: Resource annotations on the methods of the org.eclipse.jnosql.mapping.DefaultSorts class will be ignored. The annotations could not be obtained because of the exception : java.lang.NoClassDefFoundError: jakarta/nosql/Sort

[INFO] [ERROR   ] CWWKZ0004E: An exception occurred while starting the application jnosql. The exception message was: com.ibm.ws.container.service.state.StateChangeException: java.util.ServiceConfigurationError: Error instantiating :org.eclipse.jnosql.mapping.reflection.ClassMappingExtension

**Comment by otaviojava** [comment]
Could you update with this PR?
https://github.com/asterisk360-admin/jnosql-openliberty/pull/2/

**Comment by otaviojava** [comment]
@asterisk360-admin 
I checked the code and it looks ok.
I did not understand why several: `java.lang.NoClassDefFoundError` of JNoSQL library once those are on the dependency.
Could you explain to me what you're doing to execute this code?

**Comment by asterisk360-admin** [comment]
Hello @otaviojava and thanks for the reply

I update and clean the code (https://github.com/asterisk360-admin/jnosql-openliberty)

The goal of this example is make a basic hello world for the  jnosql using openliberty, rest, cdi, microprofile and mongodb


The flow is the next:
PersonApi =>> PersonDAO =>> PersonRepository =>> MongoDB


All loks fine but i get the java.lang.NoClassDefFoundError.


Really apreciated your help


Regards

**Comment by otaviojava** [comment]
I don't have expertise in open liberty.
But, there are some who to include these libraries to avoid this exception.

I have this sample code here it might help:
* https://github.com/platformsh-examples/payara-micro/tree/master/nosql
* https://github.com/platformsh-examples/deploy-friday-ep15

**Comment by asterisk360-admin** [comment]
Hello @otaviojava 

The only diference with the payara example is the pom.xml

**Payara Example:**
        <dependency>
            <groupId>org.eclipse.jnosql.artemis</groupId>
            <artifactId>artemis-document</artifactId>
            <version>0.1.0.M1</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jnosql.diana</groupId>
            <artifactId>mongodb-driver</artifactId>
            <version>0.1.0.M1</version>
        </dependency>

**OpenLiberty Example:**
        
		<dependency>
			<groupId>org.eclipse.jnosql.mapping</groupId>
		    <artifactId>mapping-document</artifactId>
		    <version>1.0.0-b3</version>
		</dependency>
		
		<dependency>
		    <groupId>org.eclipse.jnosql.communication</groupId>
		    <artifactId>mongodb-driver</artifactId>
		    <version>1.0.0-b3</version>
		</dependency>

Another config to review is in microprofile.config:
document.provider=org.eclipse.jnosql.diana.mongodb.document.MongoDBDocumentConfiguration
its not found for liberty.

**Comment by otaviojava** [comment]
I don't have the know-how to use open liberty. 
Hey, @Linuem could you help us with this issue? Could you create a sample application?

**Comment by asterisk360-admin** [comment]
Hello

For fix, add this depencies in pom and add them to copy global libs for liberty
jakarta.nosql.communication
communication-document
1.0.0-b3

jakarta.nosql.mapping
mapping-document
1.0.0-b3

update the microprofile config:
document.provider=org.eclipse.jnosql.communication.mongodb.document.MongoDBDocumentConfiguration

--
Now i'm having new error:
[INFO] [ERROR   ] CWWKZ0002E: An exception occurred while starting the application jnosql. The exception message was: com.ibm.ws.container.service.state.StateChangeException: java.util.ServiceConfigurationError: Error instantiating :org.eclipse.jnosql.mapping.reflection.ClassMappingExtension

Really aprecited your help.

**Comment by otaviojava** [comment]
Sorry by the delay.
@asterisk360-admin do you still need help?
