### ISSUE TITLE
Improving of the first Chapters' introduction content - 2.

### ISSUE THREAD

**Issue by DmitriGit** [eclipse-ee4j/nosql#80]
Hi Team,

another observation for improving content of the Introduction to "Chapter 1"...

I think that the piece:
"_Vendor lock-in is one of the things any Java project needs to consider when choosing NoSQL databases. If there’s a need for a switch, other considerations include: time spent on the change, the learning curve of a new API to use with this database, the code that will be lost, the persistence layer that needs to be replaced, etc. Jakarta NoSQL avoids most of these issues through the Communication APIs. It also has template classes that apply the design pattern 'template method’ to databases operations. And the Repository interface allows Java developers to create and extend interfaces, with implementation automatically provided by a Jakarta NoSQL implementation: support method queries built by developers will automatically be implemented for them._"

should become:
"_Vendor lock-in is one of the things any Java project needs to consider when choosing NoSQL databases. If there’s a need for a switch, other considerations include: time spent on the change, the learning curve of a new API to use with this database, the code that will be lost, the persistence layer that needs to be replaced, etc. Jakarta NoSQL avoids most of these issues through the **APIs of Communication and Mapping Layers**. 

**Jakarta NoSQL** also has template classes that apply the design pattern 'template method’ to databases operations. And the Repository interface allows Java developers to create and extend interfaces, with implementation automatically provided by a Jakarta NoSQL implementation: support method queries built by developers will automatically be implemented for them._"

Let me know if my proposal make the content more structural and more understandable to readers.

Thank you,
Dmitri.

**Comment by otaviojava** [comment]
Hey @DmitriGit 
What do you think if you do a PR with this suggestion?

**Comment by DmitriGit** [comment]
Yes, yes! Thank you very much, Otavio!
PR only for this issue 80 or for 79 also?

**Comment by otaviojava** [comment]
To both.
