### ISSUE TITLE
Define the package name domain to key-value.

### ISSUE THREAD

**Issue by otaviojava** [eclipse-ee4j/nosql#9]
As you know Jakarta NoSQL has one API to cover these NoSQL databases:
* Column
* Document
* Graph
* key-value

The domain to the first one is elementary, once we are talking about a sample name:

* jakarta.nosql.column
* jakarta.nosql.document
* jakarta.nosql.graph

The key-value is a bit difficult one even if we take a look at the convention:
https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

I have some suggestions:

* jakarta.nosql.value
* jakarta.nosql.kv (my favorite one and what [Oracle NoSQL is using](https://docs.oracle.com/database/nosql-12.1.4.2/javadoc/index.html))
* any other options?

What do you think?

**Comment by marcoantoniobferreira** [comment]
jakarta.nosql.kv looks good =)

**Comment by keilw** [comment]
It's a little short, maybe "keyvalue" is a bit clearer, but as a module name I guess I could live with it if the majority wants the short form.

**Comment by otaviojava** [comment]
Yes, Spring Data uses the same nomenclature.
So, +1 for keyvalue as well

**Comment by otaviojava** [comment]
I'll keep keyvalue:

https://www.eclipse.org/lists/jnosql-dev/msg00425.html
